apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  labels:
    app: logstash
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => json
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch-service.default.svc.cluster.local:9200"]
        index => "logs-%{+YYYY.MM.dd}"
      }
    }
