apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: default
  labels:
    app: elasticsearch
data:
  elasticsearch.yml: |
    cluster.name: "elasticsearch-cluster"
    network.host: 0.0.0.0
    node.name: "node-1"
    discovery.seed_hosts: []
    cluster.initial_master_nodes: ["node-1"]
