apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-service
  namespace: default
  labels:
    app: movie-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movie-service
  template:
    metadata:
      labels:
        app: movie-service
    spec:
      containers:
        - name: movie-service
          image: movie-service:1.0.0
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: movie-service-config
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: movie-service-config