apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
  labels:
    app: prometheus
data:
  prometheus.yml: >
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'theater-service'
        metrics_path: '/theaters/actuator/prometheus' # Specify the correct path
        static_configs:
          - targets: ['theater-service.default.svc.cluster.local:8081'] # Use port-forwarded address
            labels:
              service: 'theater-service'

      - job_name: 'booking-service'
        metrics_path: '/bookings/actuator/prometheus' # Specify the correct path
        static_configs:
          - targets: ['booking-service.default.svc.cluster.local:8084']
            labels:
              service: 'booking-service'

      - job_name: 'movie-service'
        metrics_path: '/movies/actuator/prometheus' # Specify the correct path
        static_configs:
          - targets: ['movie-service.default.svc.cluster.local:8083']
            labels:
              service: 'movie-service'